moonrepo/proto

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/lib.rs, crates/core/Cargo.toml, crates/core/src/resolver.rs, crates/core/src/verifier.rs, crates/deno/Cargo.toml, crates/deno/src/detect.rs, crates/deno/src/download.rs, crates/deno/src/execute.rs, crates/deno/src/install.rs, crates/deno/src/lib.rs, crates/deno/src/platform.rs, crates/deno/src/resolve.rs, crates/deno/src/shim.rs, crates/deno/src/verify.rs, crates/deno/tests/deno_test.rs, crates/go/src/download.rs, crates/go/src/resolve.rs, crates/go/src/verify.rs, crates/go/tests/go_test.rs, crates/node/src/depman/verify.rs, crates/node/src/verify.rs, crates/node/tests/node_depman_test.rs
Based on https://github.com/denoland/deno_install
=> new: Add Deno as a supported tool.

crates/go/src/resolve.rs, crates/go/src/verify.rs, crates/go/tests/go_test.rs
Broke this after my last refactor.
=> fix: Fix invalid Go sha256 path.

crates/deno/src/download.rs, crates/go/src/download.rs, crates/node/src/download.rs
For https://github.com/moonrepo/moon/issues/642
=> new: Support FreeBSD, OpenBSD, and other unix distros.

Cargo.lock, crates/bun/Cargo.toml, crates/bun/src/detect.rs, crates/bun/src/download.rs, crates/bun/src/execute.rs, crates/bun/src/install.rs, crates/bun/src/lib.rs, crates/bun/src/platform.rs, crates/bun/src/resolve.rs, crates/bun/src/shim.rs, crates/bun/src/verify.rs, crates/bun/tests/bun_test.rs, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/lib.rs, crates/deno/tests/deno_test.rs, crates/go/src/verify.rs, crates/go/tests/go_test.rs, crates/node/src/depman/download.rs, crates/node/src/depman/verify.rs, crates/node/tests/node_depman_test.rs, crates/node/tests/node_test.rs
Based on https://bun.sh/docs/installation
=> new: Add Bun as a supported tool.

.github/workflows/ci.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/bin.rs, crates/cli/src/commands/mod.rs, crates/cli/src/commands/setup.rs, crates/core/Cargo.toml, crates/core/src/errors.rs, release/Dockerfile, rust-toolchain.toml
This will modify the users shell and set the appropriate env vars.
=> new: Add `proto setup` command.

crates/bun/src/download.rs, crates/bun/src/lib.rs, crates/bun/src/shim.rs, crates/core/src/detector.rs, crates/core/src/shimmer.rs, crates/core/templates/bash.tpl, crates/core/templates/batch.tpl, crates/core/templates/pwsh.tpl, crates/core/templates/pwsh_global.tpl, crates/deno/src/lib.rs, crates/deno/src/shim.rs, crates/deno/tests/deno_test.rs, crates/go/src/lib.rs, crates/go/src/shim.rs, crates/go/tests/go_test.rs, crates/node/src/depman/shim.rs, crates/node/src/platform.rs, crates/node/src/shim.rs, crates/node/tests/node_depman_test.rs, crates/node/tests/node_test.rs
This works in all my testing but I'm not 100% sure it covers all edge cases.
=> new: Add Windows shims support.

crates/cli/src/app.rs, crates/cli/src/bin.rs, crates/cli/src/commands/bin.rs, crates/cli/src/commands/completions.rs, crates/cli/src/commands/global.rs, crates/cli/src/commands/install.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/commands/list.rs, crates/cli/src/commands/list_remote.rs, crates/cli/src/commands/local.rs, crates/cli/src/commands/run.rs, crates/cli/src/commands/setup.rs, crates/cli/src/commands/uninstall.rs, crates/cli/src/config.rs, crates/cli/src/helpers.rs, crates/cli/src/lib.rs, crates/cli/src/tools.rs
We're going to use this in moon.
=> new: Export `Config` from library.

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands/global.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/helpers.rs, crates/cli/tests/bin_test.rs, crates/cli/tests/global_test.rs, crates/cli/tests/install_uninstall_test.rs, crates/cli/tests/list_remote_test.rs, crates/cli/tests/local_test.rs, crates/cli/tests/run_test.rs, crates/cli/tests/use_test.rs, crates/cli/tests/utils.rs
=> tests: Add tests for commands.

Cargo.lock, Cargo.toml, crates/core/src/detector.rs
OpenSSL causes far too many issues.
=> fix: Switch to rustls from openssl.

CHANGELOG.md, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/bin.rs, crates/cli/src/commands/global.rs, crates/cli/src/commands/install.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/commands/list.rs, crates/cli/src/helpers.rs, crates/cli/tests/install_uninstall_test.rs, crates/core/src/manifest.rs, crates/node/src/depman/resolve.rs, crates/node/src/lib.rs, crates/node/src/platform.rs
Implements https://github.com/moonrepo/proto/issues/32
=> new: Support installing bundled npm.

CHANGELOG.md, crates/cli/src/commands/setup.rs, crates/cli/src/hooks/go.rs, crates/cli/src/shell.rs
Instead of erroring, let's just fallback.
=> fix: Fix shell not being detected during setup.

CHANGELOG.md, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands/install.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/commands/uninstall.rs, crates/cli/src/commands/upgrade.rs, crates/cli/src/helpers.rs, crates/node/src/download.rs
Adds loaders when installing, uninstalling, and upgrading.
=> new: Add progress bars/spinners.

CHANGELOG.md, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/bin.rs, crates/cli/src/commands/clean.rs, crates/cli/src/commands/mod.rs, crates/core/src/manifest.rs
This can be used to delete stale/old tools.
=> new: Add `clean` command.

.github/workflows/ci.yml, CHANGELOG.md, crates/cli/src/app.rs, crates/cli/src/bin.rs, crates/cli/src/commands/clean.rs, crates/cli/src/commands/install_all.rs, crates/core/src/user_config.rs
Adds a `--yes` option and an `auto-clean` setting.
=> new: Improvements to cleaning.

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/bin.rs, crates/cli/src/commands/global.rs, crates/cli/src/commands/install_global.rs, crates/cli/src/commands/local.rs, crates/cli/src/commands/setup.rs, crates/cli/src/shell.rs, crates/cli/tests/utils.rs, crates/core/src/detector.rs, crates/core/src/downloader.rs, crates/core/src/installer.rs, crates/core/src/manifest.rs, crates/core/src/resolver.rs, crates/core/src/shimmer.rs, crates/core/src/tool.rs, crates/core/src/verifier.rs, crates/go/src/verify.rs, crates/node/src/verify.rs
Instead of interpolating into the message string.
=> internal: Update log messages to use field data.

.prototools, CHANGELOG.md, crates/cli/tests/plugins_test.rs, crates/cli/tests/utils.rs, crates/core/src/manifest.rs
Fixes in comments.
Fixes https://github.com/moonrepo/proto/issues/85
=> fix: Improve file locking logic.

CHANGELOG.md, crates/cli/src/commands/bin.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/commands/run.rs, crates/cli/tests/use_test.rs, crates/core/src/detector.rs, crates/core/tests/detector_test.rs, crates/node/src/depman/detect.rs, crates/node/src/depman/resolve.rs, crates/node/src/detect.rs, crates/node/tests/node_depman_test.rs, crates/node/tests/node_test.rs
Will now check the local manifest more often, resulting in far less unnecessary tool installs.
=> new: Improve version detection matching.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/bin.rs, crates/cli/src/commands/clean.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/states.rs, crates/core/Cargo.toml
Forgot to do this for `proto clean`.
=> fix: Support cleaning plugins.

CHANGELOG.md, crates/core/src/tool.rs, crates/rust/src/execute.rs, crates/rust/src/install.rs, crates/rust/src/lib.rs
Noticed them while adding Rust tier 2/3 support to moon.
=> fix: Fix some Rust issues.

.github/workflows/release.yml, Cargo.toml
https://opensource.axo.dev/cargo-dist/changelog/v0.0.6.html
=> build: Update cargo-dist to v0.0.6.

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, crates/bun/src/shim.rs, crates/cli/Cargo.toml, crates/cli/src/commands/upgrade.rs, crates/core/Cargo.toml, crates/core/src/shimmer.rs, crates/core/src/tool.rs, crates/deno/src/shim.rs, crates/go/src/shim.rs, crates/node/src/depman/shim.rs, crates/node/src/shim.rs, crates/rust/src/shim.rs, crates/schema-plugin/Cargo.toml, crates/schema-plugin/src/shim.rs, crates/schema-plugin/tests/schema_test.rs
My recent shim changes (https://github.com/moonrepo/proto/pull/90) resulted in shims "not being found", especially in moon.
I don't like the changes I made here, but it was the easiest solution. I probably need to redo the shim layer.
=> fix: Fix shims not being found.

CHANGELOG.md, Cargo.lock, crates/cli/tests/bin_test.rs, crates/core/src/shimmer.rs, crates/node/Cargo.toml, crates/node/src/depman/execute.rs, crates/node/src/depman/shim.rs, crates/node/tests/node_depman_test.rs
Fixes https://github.com/moonrepo/proto/issues/102
=> new: Create a `node-gyp` global shim.

CHANGELOG.md, crates/bun/src/shim.rs, crates/cli/src/app.rs, crates/cli/src/bin.rs, crates/cli/src/commands/run.rs, crates/cli/tests/run_test.rs, crates/core/src/shimmer.rs, crates/core/templates/bash_global.tpl, crates/core/templates/pwsh_global.tpl, crates/deno/src/shim.rs, crates/go/src/shim.rs, crates/node/src/depman/shim.rs, crates/node/src/shim.rs, crates/schema-plugin/src/shim.rs
The previous approach was kind of gross.
=> new: Better handling of alternate tool binaries.

CHANGELOG.md, crates/cli/src/commands/run.rs, crates/cli/src/hooks/mod.rs, crates/cli/src/hooks/node.rs, crates/cli/tests/run_lang_test.rs
Fixes: https://github.com/moonrepo/proto/issues/101 https://github.com/moonrepo/proto/issues/108 https://github.com/moonrepo/proto/issues/60
=> new: Error when installing a global with npm/pnpm/yarn directly.

CHANGELOG.md, crates/cli/src/commands/upgrade.rs
For https://github.com/moonrepo/proto/issues/93
Not sure this will work.
=> fix: Attempt to fix proto killed after upgrade.

CHANGELOG.md, crates/cli/src/hooks/node.rs
Fixes https://github.com/moonrepo/proto/issues/112
=> fix: Fix yarn out of bounds error.

CHANGELOG.md, crates/cli/src/commands/upgrade.rs, crates/core/src/detector.rs, crates/core/tests/detector_test.rs
Fixes https://github.com/moonrepo/proto/issues/121
=> fix: Fix version requirement parsing for ranges.

crates/cli/src/shell.rs, crates/node/src/download.rs
=> Fix installs for node@<16 on m1 macs

CHANGELOG.md, crates/cli/src/commands/run.rs, crates/cli/src/hooks/node.rs, crates/cli/tests/run_lang_test.rs, crates/core/src/user_config.rs
Fixes https://github.com/moonrepo/proto/issues/127
=> new: Add `node-intercept-globals` setting.

CHANGELOG.md, crates/bun/src/shim.rs, crates/cli/tests/fixtures/moon-schema.toml, crates/core/src/shimmer.rs, crates/core/src/tool.rs, crates/core/templates/bash_global.tpl, crates/core/templates/bash_local.tpl, crates/core/templates/cmd_global.tpl, crates/core/templates/pwsh_global.tpl, crates/core/templates/pwsh_local.tpl, crates/deno/src/shim.rs, crates/go/src/shim.rs, crates/node/src/depman/shim.rs, crates/node/src/shim.rs, crates/schema-plugin/src/shim.rs, crates/schema-plugin/tests/schema_test.rs
The `ShimBuilder` was way too complicated. This simplifies shims overall.
=> internal: Refactor shims.

CHANGELOG.md, crates/bun/src/shim.rs, crates/core/src/shimmer.rs, crates/core/templates/bash_global.tpl, crates/core/templates/bash_local.tpl, crates/core/templates/cmd_global.tpl, crates/core/templates/pwsh_global.tpl, crates/core/templates/pwsh_local.tpl, crates/node/src/depman/shim.rs
Now that we have a better shim system, this is easier to do.
=> new: Support bunx, pnpx, and more.

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, crates/pdk-api/src/api.rs, crates/pdk-api/src/host_funcs.rs, crates/pdk-test-utils/Cargo.toml, crates/pdk-test-utils/src/lib.rs, crates/pdk-test-utils/src/macros.rs, crates/pdk-test-utils/src/wrapper.rs, crates/wasm-plugin/src/detect.rs, crates/wasm-plugin/src/host_funcs.rs, crates/wasm-plugin/src/lib.rs, crates/wasm-plugin/src/resolve.rs, plugins/Cargo.lock, plugins/wasm-test/src/lib.rs
This makes it much easier to write and test plugins.
=> new: Add WASM test utils package.

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, crates/cli/src/commands/global.rs, crates/cli/src/commands/list_global.rs, crates/cli/src/commands/local.rs, crates/cli/src/commands/plugins.rs, crates/cli/src/commands/run.rs, crates/core/src/error.rs, crates/core/src/tool.rs, crates/core/src/version_detector.rs, crates/core/src/version_resolver.rs, crates/core/tests/version_resolver_test.rs, crates/pdk-api/src/api.rs, crates/pdk/src/macros.rs
Rust is very unique. Hopefully this works...
=> internal: More changes to support Rust.

CHANGELOG.md, crates/cli/src/commands/setup.rs, crates/cli/src/hooks/go.rs, crates/cli/src/shell.rs
Fixes https://github.com/moonrepo/proto/issues/167
=> fix: Fix `proto setup` setup detection.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/helpers.rs, crates/core/src/tool.rs, crates/core/src/tool_manifest.rs
Fixes https://github.com/moonrepo/proto/issues/174
=> fix: Add file locking to versions cache.

CHANGELOG.md, crates/cli/src/commands/clean.rs, crates/cli/tests/clean_test.rs
=> fix: Delete shims when purging a tool.

CHANGELOG.md, crates/cli/src/commands/run.rs, crates/core/src/helpers.rs
- Uses `pwsh` when available.
- Uses a command approach instead of file.
=> fix: Fix some Windows issues.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/clean.rs, crates/cli/src/commands/install.rs, crates/cli/tests/plugins_test.rs, crates/core/src/tool.rs, crates/pdk-test-utils/src/lib.rs, plugins/Cargo.lock
Right now the plugins dir keeps growing.
=> new: Auto-clean plugins after an install.

CHANGELOG.md, crates/cli/src/commands/run.rs, crates/core/src/helpers.rs, crates/core/src/tool_manifest.rs, crates/pdk-test-utils/src/lib.rs
For https://github.com/moonrepo/proto/issues/85
=> fix: Attempt to fix manifest race conditions.

CHANGELOG.md, Cargo.lock, crates/cli/src/commands/install.rs, crates/cli/src/commands/pin.rs, crates/cli/tests/install_uninstall_test.rs, crates/core/src/user_config.rs, crates/core/tests/user_config_test.rs, crates/version-spec/Cargo.toml, crates/version-spec/src/resolved_spec.rs, crates/version-spec/src/unresolved_spec.rs
This setting accepts "global" or "local" and will automatically pin a tool if installing with the "latest" version.
=> new: Add `pin-latest` setting.

CHANGELOG.md, crates/cli/src/main.rs, crates/core/src/helpers.rs, crates/core/src/tool.rs
Look's like our tracing layer were intercepting logs.
=> fix: Fix WASM logs not showing up.

CHANGELOG.md, crates/core/src/error.rs, crates/pdk/src/macros.rs, crates/wasm-plugin/src/host_funcs.rs, plugins/Cargo.lock, plugins/wasm-test/src/lib.rs
=> new: Add environment variable host functions.

CHANGELOG.md, Cargo.lock, crates/core/Cargo.toml, crates/core/src/error.rs, crates/core/src/tool.rs, crates/pdk-api/src/api.rs, plugins/Cargo.lock, plugins/wasm-test/src/lib.rs
https://jedisct1.github.io/minisign/
=> new: Add minisign support.

Cargo.lock, Cargo.toml, crates/cli/tests/install_uninstall_test.rs, crates/cli/tests/utils.rs, crates/core/src/tool.rs, crates/pdk-test-utils/src/lib.rs, crates/pdk-test-utils/src/macros.rs, crates/pdk/Cargo.toml, crates/pdk/src/helpers.rs
Noticed this has broken recently.
Really need a better way to verify these.
=> internal: Ensure test macros work correctly.

CHANGELOG.md, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands/alias.rs, crates/cli/src/commands/clean.rs, crates/cli/src/commands/install.rs, crates/cli/src/commands/install_global.rs, crates/cli/src/commands/list_global.rs, crates/cli/src/commands/migrate/mod.rs, crates/cli/src/commands/outdated.rs, crates/cli/src/commands/remove_plugin.rs, crates/cli/src/commands/run.rs, crates/cli/src/commands/tools.rs, crates/cli/src/commands/uninstall_global.rs, crates/cli/src/commands/upgrade.rs, crates/cli/src/error.rs, crates/cli/src/main.rs, crates/cli/tests/alias_test.rs, crates/cli/tests/remove_plugin_test.rs, crates/core/src/tool.rs, crates/pdk-api/src/api.rs
This causes a lot of problems...
=> new: Block tools from self-upgrading.

CHANGELOG.md, crates/core/src/error.rs, crates/core/src/helpers.rs, crates/core/src/proto.rs, crates/core/src/tool.rs, crates/warpgate/src/error.rs, crates/warpgate/src/loader.rs, docs/debugging.md
For https://github.com/moonrepo/proto/issues/246
=> internal: Improve offline handling.

CHANGELOG.md, crates/cli/src/commands/install.rs, crates/cli/src/commands/run.rs, crates/cli/src/helpers.rs, crates/cli/tests/run_test.rs, crates/core/src/proto.rs, crates/core/src/tool_loader.rs
Problem was that the manifest state was lost. This fixes it by reusing the tool instance.
Fixes https://github.com/moonrepo/proto/issues/254
=> fix: Fix auto-install re-installing tools.

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, crates/cli/Cargo.toml, crates/cli/tests/utils.rs, crates/core/Cargo.toml, crates/core/src/helpers.rs, crates/core/src/tool.rs, crates/core/src/tool_manifest.rs, crates/pdk-test-utils/src/macros.rs, plugins/Cargo.lock, plugins/Cargo.toml
Fix was in starbase https://github.com/moonrepo/starbase/pull/47
=> new: Rework directory locking and the install target.

CHANGELOG.md, crates/core/src/helpers.rs, crates/core/src/tool.rs
Noticed these issues while using proto.
=> fix: Audit 11/02

CHANGELOG.md, crates/cli/src/commands/bin.rs, crates/cli/src/commands/migrate/v0_20.rs, crates/core/src/error.rs, crates/core/src/proto.rs, crates/core/src/tool.rs, crates/core/src/tool_loader.rs, crates/core/src/tools_config.rs, crates/core/src/version_detector.rs, crates/pdk-test-utils/src/macros.rs, crates/warpgate/src/loader.rs
This will ideally reduce the checks to 0 for `proto run` flows if the cache exists.
=> new: Reduce internet connection checks.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/commands/run.rs, crates/core/Cargo.toml, crates/core/src/shimmer.rs, crates/core/src/tool.rs, crates/core/templates/bash_global.tpl, crates/core/templates/cmd_global.tpl, crates/core/templates/pwsh_global.tpl, crates/core/tests/shimmer_test.rs, crates/core/tests/snapshots/shimmer_test__shimmer__alt_global.snap, crates/core/tests/snapshots/shimmer_test__shimmer__alt_global_with_args.snap, crates/pdk-api/Cargo.toml, crates/pdk-api/src/api.rs, crates/pdk-test-utils/Cargo.toml, crates/pdk/Cargo.toml, crates/system-env/Cargo.toml, crates/version-spec/Cargo.toml, crates/warpgate-api/Cargo.toml, crates/warpgate/Cargo.toml
Using the npm/pnpm/yarn shell scripts directly caused a bunch of problems.
=> internal: Bring back parent executable concept.

CHANGELOG.md, crates/cli/src/commands/clean.rs, crates/cli/src/commands/install_all.rs, crates/cli/tests/clean_test.rs
Fixes: https://github.com/moonrepo/proto/issues/278
=> fix: Fix clean crashing when loading the schema plugin.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/clean.rs, crates/cli/tests/clean_test.rs, crates/core/src/tool.rs
Fixes https://github.com/moonrepo/proto/issues/293
=> fix: Fix broken symlinks not being removed. 

CHANGELOG.md, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands/run.rs, crates/core/Cargo.toml, crates/core/src/host_funcs.rs, crates/system-env/Cargo.toml, crates/system-env/src/env.rs, crates/system-env/src/helpers.rs, crates/system-env/src/lib.rs
Fixes https://github.com/moonrepo/proto/issues/296
=> fix: Find absolute bins before executing commands.

CHANGELOG.md, crates/core/src/version_resolver.rs
Fixes https://github.com/moonrepo/proto/issues/299
=> fix: Fix multi-range version detection.

CONTRIBUTING.md
Close #39 
In my free time, sometimes I stopping by and read this repo to understand and if possible, solve my own bug or at least understand why that bug happen. For now, I just write this `CONTRIBUTING.md` for anyone who willing to contribute to this repo.
=> Add CONTRIBUTING.md file with guidelines for contributing to Proto

.prototools, CHANGELOG.md, crates/cli/src/systems.rs, crates/core/src/proto.rs, crates/core/src/proto_config.rs, crates/core/src/tool_loader.rs, crates/core/tests/proto_config_test.rs, crates/pdk/src/helpers.rs, crates/warpgate/src/error.rs, crates/warpgate/src/plugin.rs, plugins/wasm-test/src/lib.rs
Implements https://github.com/moonrepo/proto/issues/261
=> new: Support tool-level config.

CHANGELOG.md, crates/cli/src/commands/list.rs, crates/cli/src/commands/list_remote.rs, crates/cli/src/commands/tool/info.rs, crates/cli/src/commands/tool/list.rs, crates/cli/src/printer.rs, crates/core/src/proto_config.rs, crates/core/src/version_resolver.rs
=> new: Bubble up aliases information.

CHANGELOG.md, crates/cli/src/commands/install.rs, crates/cli/tests/plugins_test.rs, crates/core/src/proto_config.rs
=> fix: Audit 12/13

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/main_shim.rs, crates/core/src/shim_registry.rs
=> new: Replace serde_json with rust_json.

Cargo.lock, crates/cli/Cargo.toml, crates/installer/Cargo.toml
Ran into issues with the features.
=> internal: Publish installer crate.

CHANGELOG.md, crates/cli/src/shell.rs
Fixes https://github.com/moonrepo/proto/issues/361
=> fix: Fix Elvish profile setup.

CHANGELOG.md, crates/cli/src/main_shim.rs, crates/cli/tests/shim_test.rs
Fixes https://github.com/moonrepo/proto/issues/373
=> fix: Lowercase shim name before executing.

CHANGELOG.md, crates/cli/src/commands/clean.rs, crates/cli/src/commands/run.rs, crates/cli/src/commands/tool/list.rs, crates/cli/tests/run_test.rs, crates/core/src/tool_manifest.rs
I believe this is causing race conditions with the manifest, and why the manifest sometimes gets reset.
=> internal: Rework "last used at" logic.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/commands/upgrade.rs, crates/cli/src/helpers.rs, crates/cli/src/main.rs, crates/cli/src/systems.rs, crates/cli/src/telemetry.rs, crates/cli/tests/utils.rs, crates/core/src/helpers.rs, crates/core/src/tool_manifest.rs
Let people know they're out of date!
=> new: Add proto version checks.

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, crates/cli/Cargo.toml, crates/core/src/proto_config.rs
=> internal: Update plugins.

CHANGELOG.md, crates/core/src/host_funcs.rs, crates/core/src/proto.rs, crates/pdk/src/macros.rs, crates/warpgate/src/helpers.rs, crates/warpgate/src/plugin.rs, plugins/Cargo.lock, plugins/wasm-test/src/lib.rs
Fixes https://github.com/moonrepo/proto/issues/390
=> new: Support modifying `PATH` from WASM.

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/commands/clean.rs, crates/cli/src/commands/outdated.rs, crates/cli/src/commands/tool/list.rs, crates/cli/src/helpers.rs, crates/cli/src/telemetry.rs, crates/cli/tests/install_uninstall_test.rs, crates/core/Cargo.toml, crates/core/src/proto_config.rs, crates/core/src/shim_registry.rs, crates/core/src/tool.rs, crates/core/src/tool_manifest.rs, crates/core/src/user_config.rs, crates/core/src/version_resolver.rs, crates/core/tests/proto_config_test.rs, crates/pdk-api/Cargo.toml, crates/pdk-api/src/api.rs, crates/pdk/Cargo.toml, crates/pdk/src/helpers.rs, crates/warpgate-api/Cargo.toml, crates/warpgate-api/src/host_funcs.rs, crates/warpgate-api/src/lib.rs, crates/warpgate/Cargo.toml
=> internal: Migrate to Fx collections.

.github/workflows/ci.yml, CHANGELOG.md, crates/cli/src/app.rs, crates/cli/src/commands/install.rs, crates/cli/src/commands/setup.rs, crates/cli/src/helpers.rs, crates/cli/src/shell.rs, crates/core/src/proto_config.rs
=> new: Update `proto setup` to be interactive.

CHANGELOG.md, crates/cli/src/commands/install.rs, crates/cli/src/commands/setup.rs, crates/core/src/proto.rs, crates/core/src/proto_config.rs
This actually causes problems being in the config.
=> internal: Move profile path out of config.

CHANGELOG.md, crates/cli/src/shell.rs
Fixes https://github.com/moonrepo/proto/issues/435
=> fix: Fix newlines in pwsh profiles.

CHANGELOG.md, crates/cli/src/commands/clean.rs, crates/cli/src/commands/plugin/list.rs, crates/cli/src/commands/run.rs, crates/core/src/layout/inventory.rs, crates/core/src/layout/product.rs, crates/core/src/tool.rs, crates/shim/src/lib.rs
Fixes https://github.com/moonrepo/proto/issues/443
=> fix: Fix version suffix missing from non-versions.

Cargo.lock, Cargo.toml, crates/codegen/Cargo.toml, crates/codegen/src/main.rs, crates/core/Cargo.toml, crates/core/src/backends/mod.rs, crates/core/src/backends/proto/data.rs, crates/core/src/backends/proto/mod.rs, crates/core/src/lib.rs, crates/pdk-api/Cargo.toml, justfile, package/src/api-types.ts, registry/built-in.json, registry/data/built-in.json, registry/data/third-party.json, registry/schema.json
This will be the source of truth for now.
=> new: Add registry data for all available tools.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/codegen/src/main.rs, crates/pdk-api/src/api/build_source.rs, crates/pdk-api/src/api/mod.rs, crates/pdk-api/src/hooks.rs, crates/warpgate-api/src/host.rs, crates/warpgate-api/src/host_funcs.rs, crates/warpgate-api/src/lib.rs, package/src/api-types.ts
This gives us proper TS types.
=> internal: Rework serde defaults.

CHANGELOG.md, crates/core/src/layout/store.rs, crates/core/src/tool.rs, crates/shim/src/unix.rs, crates/shim/src/windows.rs
Hopefully this fixes some race conditions I've been seeing.
=> new: Lock bin/shims directories when creating files.

registry/data/third-party.json
I must've forgotten to change this when copy pasta-ing 🍝
=> fix: update third-party.json author typo

Cargo.lock, Cargo.toml, crates/cli/src/main.rs
=> internal: Upgrade starbase again.

CHANGELOG.md, crates/cli/src/commands/upgrade.rs, crates/installer/src/error.rs, crates/installer/src/lib.rs
Fixes https://github.com/moonrepo/proto/issues/521
=> fix: Fix release not being available when installing.

crates/system-env/src/deps.rs
=> chore: update deps.rs

crates/cli/src/app.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/commands/mod.rs, crates/cli/src/main.rs, crates/cli/tests/use_test.rs
=> feat: add --include-global support to proto use

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/install.rs, crates/cli/src/commands/setup.rs, crates/cli/src/shell.rs, crates/cli/tests/utils.rs
Fixes https://github.com/moonrepo/proto/issues/541
=> fix: Improve shell profile updating.

CHANGELOG.md, crates/cli/tests/plugins_test.rs, crates/core/src/proto_config.rs, crates/core/src/tool_loader.rs, crates/core/tests/proto_config_test.rs, crates/core/tests/version_detector_test.rs
Fixes https://github.com/moonrepo/proto/issues/546
=> new: Add `builtin-plugins` setting.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/clean.rs, crates/cli/src/commands/setup.rs, crates/cli/src/commands/uninstall.rs, package/src/api-types.ts
Fixes https://github.com/moonrepo/proto/issues/545
=> new: Support env vars for `proto setup`.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/bin.rs, crates/cli/src/commands/install.rs, crates/cli/src/commands/outdated.rs, crates/cli/src/commands/status.rs, crates/cli/src/main_shim.rs, crates/cli/src/session.rs, crates/cli/src/systems.rs, crates/cli/tests/general_test.rs, crates/core/src/proto_config.rs, crates/core/tests/proto_config_test.rs, crates/shim/src/lib.rs
Implements https://github.com/moonrepo/proto/issues/547
=> new: Support pinning proto in `.prototools`.

CHANGELOG.md, crates/cli/src/commands/status.rs, crates/cli/tests/status_test.rs
This required quite a rework... but it works.
=> new: Include ecosystem files in `proto status`.

CHANGELOG.md, crates/cli/src/app.rs, crates/cli/src/commands/upgrade.rs, crates/cli/src/main.rs, crates/cli/src/session.rs, crates/core/src/proto_config.rs, crates/installer/src/lib.rs
Fixes https://github.com/moonrepo/proto/issues/570 and https://github.com/moonrepo/proto/issues/569
=> new: Improve `proto upgrade` flow.

CHANGELOG.md, crates/cli/src/commands/activate.rs
Try and squeeze some perf out.
=> fix: Filter tools during activation.

crates/cli/src/commands/install.rs, crates/cli/src/commands/run.rs, crates/cli/src/helpers.rs
Otherwise the commands feel like they're doing nothing.
=> new: Show progress state when not a TTY.

CHANGELOG.md, crates/cli/tests/activate_test.rs, crates/core/src/proto_config.rs
=> fix: Fix "all" mode not working.

registry/data/third-party.json
I added a new TOML plugin for [OpenTofu](https://opentofu.org/), the open source infrastructure as code tool.
=> Add tofu plugin

registry/data/third-party.json
Added plugins for Atlas and TFLint to the registry.
=> feat: Add third-party toml plugins: `Atlas` and `TFLint` to the registry

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/core/src/flow/install.rs, crates/core/src/proto.rs, crates/warpgate/Cargo.toml, crates/warpgate/src/client.rs, crates/warpgate/src/endpoints.rs, crates/warpgate/src/error.rs, crates/warpgate/src/helpers.rs, crates/warpgate/src/host.rs, crates/warpgate/src/loader.rs
=> new: Add netrc support and request caching.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/commands/upgrade.rs, crates/cli/src/components/issues_list.rs, crates/cli/src/error.rs
Fixes https://github.com/moonrepo/proto/issues/687
=> new: Change upgrade flow to a confirm prompt.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/diagnose.rs, crates/cli/src/commands/plugin/search.rs, crates/cli/src/commands/setup.rs, crates/cli/src/commands/versions.rs, crates/cli/src/components/code_block.rs, crates/cli/src/components/install_all_progress.rs, crates/cli/src/components/install_progress.rs, crates/cli/src/components/issues_list.rs, crates/cli/src/components/locator.rs
=> fix: Fix panic when there's no terminal width.

CHANGELOG.md, crates/cli/src/commands/uninstall.rs, crates/core/src/flow/locate.rs, crates/core/src/proto_config.rs
Primarily a fix for Python right now.
=> fix: Fix bin linking for legacy installs.

CHANGELOG.md, crates/cli/src/commands/setup.rs, crates/cli/src/main_shim.rs, crates/core/src/flow/locate.rs, crates/core/src/proto.rs
Fixes https://github.com/moonrepo/proto/issues/708
=> new: Add `$XDG_DATA_HOME` support.

crates/cli/src/helpers.rs
This change makes the version check more reliable by ensuring we only get versions that have complete release artifacts available. This prevents users from attempting to upgrade to versions where the binaries are not yet published.
=> fix: use GitHub Releases API instead of raw version file

registry/data/third-party.json
A few plugins I use for my projects. Hopefully it'll be useful for someone else too. :]
=> new: sqlc, migrate, air plugins

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/commands/alias.rs, crates/cli/src/commands/outdated.rs, crates/cli/src/commands/pin.rs, crates/cli/src/commands/plugin/add.rs, crates/cli/src/commands/plugin/remove.rs, crates/cli/src/commands/unalias.rs, crates/cli/src/commands/uninstall.rs, crates/cli/src/commands/unpin.rs, crates/cli/tests/unalias_test.rs, crates/core/Cargo.toml, crates/core/src/config.rs, crates/core/src/config_error.rs, crates/core/src/flow/setup.rs, crates/core/src/lib.rs, crates/core/tests/proto_config_test.rs, plugins/Cargo.lock
Fixes https://github.com/moonrepo/proto/issues/424
=> new: Preserve comments when updating config files.

registry/data/third-party.json
Adds a new entry to the third-party.json file in the registry, introducing support for the many plugins.
=> new: ｍany plugins
