Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/bin.rs, crates/cli/src/commands/global.rs, crates/cli/src/commands/install.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/commands/list.rs, crates/cli/src/commands/local.rs, crates/cli/src/commands/setup.rs, crates/cli/src/commands/uninstall.rs, crates/cli/src/config.rs, crates/cli/src/helpers.rs, crates/cli/src/lib.rs, crates/cli/src/manifest.rs, crates/cli/tests/global_test.rs, crates/cli/tests/install_uninstall_test.rs, crates/cli/tests/list_test.rs, crates/cli/tests/run_test.rs
This adds a new `manifest.json` that exists at the root of each installed tool (below the versions) that tracks the installed versions, the global default version, and in the future, aliases.
=> new: Add a manifest file for tracking information.

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/bin.rs, crates/cli/src/commands/global.rs, crates/cli/src/commands/install.rs, crates/cli/src/commands/list.rs, crates/cli/src/commands/uninstall.rs, crates/cli/src/helpers.rs, crates/cli/src/lib.rs, crates/core/Cargo.toml, crates/core/src/lib.rs, crates/core/src/manifest.rs
In a previous PR I added a manifest layer: https://github.com/moonrepo/proto/pull/24
While this works fine, it dawned on me that this would not work with moon, as moon does not use proto's CLI but uses the core/lang crates directly.
If someone was using moon and proto together, the manifest would get out of sync rather quickly. To remedy this, I'm moving the manifest logic into core.
=> fix: Move manifest logic to core.

crates/cli/src/app.rs, crates/cli/src/bin.rs, crates/cli/src/commands/install.rs, crates/cli/src/commands/install_all.rs, crates/cli/tests/bin_test.rs, crates/cli/tests/global_test.rs, crates/cli/tests/install_uninstall_test.rs, crates/cli/tests/local_test.rs, crates/cli/tests/run_test.rs, crates/cli/tests/use_test.rs
This allows the global version to be pinned based on the newly installed tool.
=> new: Add `--pin` flag to `install`.

crates/core/src/detector.rs, crates/node/tests/node_depman_test.rs, crates/node/tests/node_test.rs
Previously versions that started with `^`, `>=`, and other variants were ignored for detection. This will now utilize those requirements and attempt to parse them to an applicable version. This isn't perfect, but is better than nothing.
=> new: Support version requirements/ranges as possible versions.

CHANGELOG.md, Cargo.lock, crates/core/Cargo.toml, crates/core/src/detector.rs, crates/core/src/errors.rs, crates/node/src/depman/detect.rs, crates/node/src/detect.rs, crates/node/tests/node_depman_test.rs, crates/node/tests/node_test.rs
When we encounter a `^`, `>=`, or other version requirement, we compare against currently installed versions, instead of trying to resolve some random fixed version.
=> breaking: Rework handling of version requirement detection.

CHANGELOG.md, crates/bun/src/resolve.rs, crates/cli/src/commands/global.rs, crates/cli/src/commands/list_remote.rs, crates/cli/src/commands/local.rs, crates/cli/tests/global_test.rs, crates/cli/tests/install_lang_test.rs, crates/cli/tests/local_test.rs, crates/cli/tests/run_test.rs, crates/core/src/errors.rs, crates/core/src/manifest.rs, crates/core/src/resolver.rs, crates/core/src/tool.rs, crates/deno/src/resolve.rs, crates/go/src/resolve.rs, crates/node/src/depman/resolve.rs, crates/node/src/resolve.rs
With this, npm will always default to "bundled" unless explicitly overridden by a user.
=> new: Allow tools to define a default version via a trait method.

crates/cli/src/commands/install_all.rs, crates/cli/src/commands/local.rs, crates/cli/src/shell.rs, crates/core/src/detector.rs, crates/core/src/lib.rs, crates/core/src/tools_config.rs
We'll be adding another config type, so renaming to not be generic.
=> internal: Rename `Config` to `ToolsConfig`.

CHANGELOG.md, Cargo.lock, crates/bun/tests/bun_test.rs, crates/cli/Cargo.toml, crates/cli/src/commands/setup.rs, crates/cli/tests/install_lang_test.rs
This is more accurate as it doesn't pull in all system level paths, since `setx` is user level.
=> new: Use Windows Registry when setting `PATH`.

crates/cli/src/commands/install.rs, crates/core/src/installer.rs, crates/core/src/tool.rs, crates/rust/src/install.rs, crates/rust/src/lib.rs
Since Rust works differently, we need to overwrite the default functionality.
=> internal: Add an `uninstall` method to installer trait.

CHANGELOG.md, crates/cli/src/commands/bin.rs, crates/cli/src/commands/run.rs, crates/cli/tests/alias_test.rs, crates/cli/tests/global_test.rs, crates/cli/tests/install_lang_test.rs, crates/cli/tests/install_uninstall_test.rs, crates/cli/tests/list_test.rs, crates/cli/tests/run_test.rs, crates/cli/tests/unalias_test.rs, crates/core/src/detector.rs, crates/core/src/manifest.rs, crates/node/src/depman/resolve.rs
We'll be using this information for future functionality.
=> internal: Track installed at/last used at timestamps.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/clean.rs, crates/core/Cargo.toml, crates/core/src/manifest.rs
Have noticed some race conditions, especially when multiple processes are running in parallel. Let's try locking.
=> new: Add read/write file locking for the manifest.

CHANGELOG.md, crates/core/src/shimmer.rs
I think this is currently causing a "text file busy" error.
=> fix: Don't create shim if it already exists.

CHANGELOG.md, crates/cli/src/bin.rs, crates/cli/src/commands/install_all.rs, crates/cli/tests/use_test.rs, crates/schema-plugin/Cargo.toml, crates/schema-plugin/README.md
Alongside installing `.prototools`, the `use` command will also detect versions based on cwd.
=> new: Update `proto use` to detect from the ecosystem.

CHANGELOG.md, crates/core/src/detector.rs
We should always use the latest applicable version.
=> fix: Sort versions during detection.

CHANGELOG.md, crates/cli/tests/fixtures/moon-schema.toml, crates/core/src/installer.rs, crates/schema-plugin/src/install.rs, crates/schema-plugin/src/schema.rs
Some tools aren't archived, so we need to avoid unpacking.
=> new: Add `install.unpack` schema setting.

crates/bun/src/execute.rs, crates/bun/src/lib.rs, crates/bun/src/shim.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/commands/install_global.rs, crates/cli/src/commands/local.rs, crates/cli/src/commands/run.rs, crates/core/src/describer.rs, crates/core/src/detector.rs, crates/core/src/executor.rs, crates/core/src/installer.rs, crates/deno/src/execute.rs, crates/deno/src/lib.rs, crates/deno/src/shim.rs, crates/go/src/execute.rs, crates/go/src/lib.rs, crates/go/src/shim.rs, crates/node/src/depman/mod.rs, crates/node/src/execute.rs, crates/node/src/lib.rs, crates/node/src/shim.rs, crates/rust/src/install.rs, crates/rust/src/lib.rs, crates/schema-plugin/src/execute.rs, crates/schema-plugin/src/lib.rs, crates/schema-plugin/src/schema.rs, crates/schema-plugin/src/shim.rs, crates/schema-plugin/tests/schema_test.rs
Our API called it bin name, but that's not really what it was. It was the general tool ID used as a reference.
=> internal: Clean up bin name/ID confusion.

CHANGELOG.md, crates/cli/src/commands/upgrade.rs
The unzip creates `temp/proto.exe` instead of `temp/<target>/proto.exe`, which tar uses. This updates upgrade to check both patterns.
=> fix: Fix `proto upgrade` on Windows.

CHANGELOG.md, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/bin.rs, crates/core/src/shimmer.rs
We supported `PROTO_LOG`, but it wasn't very discoverable. So this adds an option.
=> new: Add a `--log` option.

Cargo.lock, crates/core/Cargo.toml, crates/core/src/detector.rs, crates/core/src/helpers.rs, crates/core/tests/detector_test.rs
Replace whitespace after `>`, `>=`, `<` and `<=` in `detector`.
It's how `node-semver` handles it: https://github.com/npm/node-semver/blob/cce61804ba6f997225a1267135c06676fe0524d2/internal/re.js#L188-L192
=> fix: Remove space after gt lt gte lte in detector

crates/core/src/tool.rs, crates/core/src/tool_manifest.rs, crates/core/src/version_detector.rs, crates/pdk-api/src/api.rs, crates/pdk-test-utils/src/wrapper.rs, crates/schema-plugin/src/schema.rs
This allows tools (like Rust) to sync their manifest when needed.
=> new: Add `sync_manifest` function.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/tests/run_test.rs, crates/core/src/shimmer.rs, crates/core/src/tool.rs, crates/core/src/tool_loader.rs, crates/core/src/tools_config.rs, crates/core/src/user_config.rs, crates/pdk-test-utils/src/lib.rs
This primarily will help for tests and task runners where multiple proto processes are running.
=> new: Add dir locks during installation.

Cargo.lock, crates/core/Cargo.toml, crates/core/src/events.rs, crates/core/src/lib.rs, crates/core/src/proto.rs, crates/core/src/tool.rs, crates/core/src/tool_loader.rs, crates/pdk/src/helpers.rs, crates/warpgate/src/loader.rs
This is primarily for moon and allows us to hook into the lifecycle.
=> internal: Add events.

.github/workflows/ci.yml, crates/pdk-test-utils/src/macros.rs, plugins/Cargo.lock, plugins/Cargo.toml, plugins/wasm-test/Cargo.toml, plugins/wasm-test/src/lib.rs, plugins/wasm-test/tests/macros_test.rs
To ensure we don't break them.
=> ci: Lint test utils macros.

CHANGELOG.md, crates/cli/src/commands/install.rs, crates/cli/tests/install_uninstall_test.rs, crates/core/src/events.rs
Fixes: https://github.com/moonrepo/proto/issues/195
=> new: Allow pin even if already installed.

CHANGELOG.md, crates/cli/src/commands/install.rs, crates/cli/src/commands/install_all.rs, crates/cli/src/commands/list_remote.rs, crates/core/src/tool.rs
Have seen a few reports where install fails for new versions, and it's because they hit the cache.
=> fix: Disable caching for install flows.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/core/src/error.rs, crates/core/src/helpers.rs, crates/core/src/proto.rs, crates/core/src/tool.rs, crates/core/src/tool_loader.rs, crates/core/src/user_config.rs, crates/core/tests/user_config_test.rs, crates/warpgate/src/client.rs, crates/warpgate/src/helpers.rs, crates/warpgate/src/lib.rs, crates/warpgate/src/loader.rs, crates/warpgate/tests/loader_test.rs
This _should_ help developers behind corporate proxies.
=> new: Add settings for controlling certs and proxies.

CHANGELOG.md, Cargo.lock, Cargo.toml
Context: https://github.com/moonrepo/proto/issues/204
This will use native certs if available.
=> fix: Switch to `rustls-tls-native-roots`.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/install.rs, crates/cli/src/commands/uninstall.rs, crates/core/src/error.rs, crates/core/src/tool.rs, crates/pdk-api/src/api.rs, plugins/Cargo.lock
Fixes https://github.com/moonrepo/proto/issues/209
=> fix: Bubble up install/uninstall failures.

crates/pdk/src/helpers.rs, crates/system-env/src/pm.rs
This uses the built-in extism functions, since it persists across function calls.
=> internal: Rework WASM fetch caching.

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, crates/warpgate/Cargo.toml, crates/warpgate/src/helpers.rs, plugins/Cargo.lock
The stable branch seems to have the memory issue, so use it for now.
=> fix: Use extism stable.

CHANGELOG.md, Cargo.lock, crates/core/src/tool.rs, crates/pdk-api/Cargo.toml, crates/pdk-api/src/api.rs, crates/pdk-api/src/lib.rs, crates/pdk-test-utils/src/wrapper.rs, crates/version-spec/src/lib.rs, plugins/Cargo.lock, plugins/wasm-test/src/lib.rs
This allows plugins to more accurately handle all the variations.
=> new: Use explicit version types in WASM API.

CHANGELOG.md, crates/cli/src/commands/clean.rs, crates/cli/src/commands/migrate/v0_20.rs, crates/cli/tests/clean_test.rs, crates/cli/tests/install_uninstall_test.rs, crates/core/src/helpers.rs, crates/core/src/tool.rs
Symlinks require admin privs, and we simply can't force all users to have to enable those settings.
=> fix: Copy bins instead of symlinking on Windows.

CHANGELOG.md, crates/cli/src/commands/list_global.rs, crates/core/src/tools_config.rs
@rotu Fixes things.
One caveat though is that Python bins and globals are the same dir, so listing globals lists a bunch of other stuff. Not sure we can work around that easily.
=> fix: Fix listing globals. Update plugins.

CHANGELOG.md, crates/cli/src/commands/install_all.rs, crates/core/src/tool_loader.rs
Should alleviate this error:
```
Error: fs::rename
× Failed to rename ~/.proto/temp/internal-schema-
│ e4bcf2a719dfcf6c7b7c768cb76bf31bfa2318e54e5cb72029b4c6616d463491.wasm
│ to ~/.proto/plugins/internal-schema-
│ e4bcf2a719dfcf6c7b7c768cb76bf31bfa2318e54e5cb72029b4c6616d463491.wasm.
╰─▶ No such file or directory (os error 2)
help: Does the source file exist?
```
=> fix: Preload schema plugin for `proto use`.

crates/core/templates/windows/cmd.tpl
The `ErrorActionPreference` and `DebugPreference` variables have no effect in batch scripts.
=> Remove vestigial variables

CHANGELOG.md, crates/cli/src/commands/outdated.rs
Don't include global by default, but add options to control all this.
=> fix: Fix `proto outdated` config eagerness.

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands/run.rs, crates/cli/src/main.rs, crates/cli/src/main_shim.rs, crates/cli/src/shared.rs, crates/cli/tests/fixtures/shim-signal.mjs, crates/cli/tests/shim_test.rs, crates/core/src/proto.rs, docs/shim-test.mjs, justfile
Uses `signal-hook` (which also has windows support) to handle signals correctly. I also wrapped the `proto run` in the same logic, since the flow is `shim -> proto run -> tool`.
=> new: Improve signal handling.

crates/cli/src/main.rs, crates/cli/src/main_shim.rs, crates/core/src/tool.rs
The shim release filesize was around 2.5mb, which is way too much. Removing `tracing` dropped it down to about 500kb... That's more like it.
To make up for the lost information, I moved some of the values around.
=> internal: Remove tracing crate.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/install_all.rs, crates/cli/src/commands/run.rs, crates/core/src/error.rs, crates/core/src/tool.rs, crates/core/src/version_detector.rs
This will help users who don't know why a certain version is being used.
=> fix: Include detection source in error messages.

crates/cli/src/shell.rs
1. Remove `str:join` usage for better portability and simplicity
using `str:join` requires `use str` first, and we can directly operate on `$paths` to avoid dealing with `:` in `PATH` manually
2. Add general logic to deal with normal env vars
relates to https://github.com/moonrepo/proto/issues/361
follows https://github.com/moonrepo/proto/pull/362
---
I'm very new to Rust and I'm afraid if I have done anything wrong here. Please point out if any exists :)
=> refactor: refine Elvish profile setup

CHANGELOG.md, crates/shim/src/windows.rs, justfile
Windows shims seems to fail in moon consistently with "Access is denied"errors: https://github.com/moonrepo/moon/actions/runs/7333162316/job/19969691809?pr=1244
I'm not entirely sure why. I'm assuming that the exe is in use by another process and renaming fails.
If we hit this error, we just return early, because it's still safe because the shim already exists anyways.
=> fix: Temporarily fix Windows shims.

CHANGELOG.md, crates/cli/src/main.rs, crates/shim/src/lib.rs
moon installs proto to `~/.proto/tools/proto/<version>`, so the shim file cannot be found in a clean environment.
=> new: Add more shim lookups.

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands/setup.rs, crates/cli/src/commands/setup/windows.rs, crates/cli/src/shell.rs
Very much inspired by rustup's implementation and in fact the low-level byte handling was copied verbatim, hence I added their MIT license. I hope this is fine with you, as I don't really know another way to achieve that part.
I added a --no-modify-path parameter to the setup command, but it's only really relevant for Windows. Should I conditionally compile it in, or is it better to keep the API identical?
I also had to restructure the setup flow quite a bit. I think I kept the same spirit of it, but let me know if you're unhappy with any of it. 
Note in the finished_message I opted for not suggesting Windows users to configure their PowerShell profile manually, and instead just tell them what to add to the system PATH if they didn't let us do it for them.
---
A final thing that just hit …
=> new: Automatically configure Windows system PATH

crates/cli/src/shell.rs
**References:**
https://zsh.sourceforge.io/Intro/intro_3.html
> `.zshenv' is sourced on all invocations of the shell, unless the -f option is set. It should contain commands to set the command search path, plus other important environment variables.
**Implementation in rustup:**
https://github.com/rust-lang/rustup/blob/f26d16b3b940bfb7b5e5aad7ee8f7121569f1d60/src/cli/self_update/shell.rs#L186-L191
=> new: use .zshenv by default

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/bin.rs, crates/core/src/tool.rs, crates/version-spec/src/resolved_spec.rs, crates/version-spec/src/unresolved_spec.rs, crates/warpgate-api/src/locator.rs, crates/warpgate-api/src/virtual_path.rs, crates/warpgate/src/id.rs, package/src/api-types.ts, plugins/Cargo.lock, plugins/Cargo.toml
This is causing race conditions (mainly in tests) where they all try to read/write to the same shim location.
=> fix: Don't force create shims during setup.

crates/version-spec/src/lib.rs
Refer to https://github.com/moonrepo/proto/issues/483 issue, some version using `v` version with inequality sign, So recognize that versions.
---
```
just test-ci
Summary [ 259.601s] 233 tests run: 233 passed, 0 skipped
```
=> fix: recognize version with start with v when leading inequality sign

CHANGELOG.md, crates/cli/src/main.rs, crates/cli/tests/outdated_test.rs, crates/cli/tests/snapshots/outdated_test__outdated__updates_each_file_respectively.snap, crates/version-spec/src/lib.rs, crates/version-spec/src/unresolved_parser.rs, crates/version-spec/src/unresolved_spec.rs, crates/version-spec/tests/unresolved_spec_test.rs
Fixes https://github.com/moonrepo/proto/issues/537
=> fix: Support `.x` in versions.

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/warpgate/Cargo.toml
proto uses reqwest for HTTP, while WASM uses ureq. The former had certs setup but the latter did not. Hopefully this helps.
=> fix: Fix some certificate issues.

crates/cli/src/commands/install.rs, crates/cli/tests/install_uninstall_test.rs, crates/core/src/flow/install.rs
This PR is a proposal to fix #618
=> fix: canary is not reinstalled unless install --force is used. #(618)

registry/data/third-party.json
Added plugins for Mockery, StaticCheck and OpenFGA to the registry.
=> feat: Add third-party toml plugins: `mockery`, `staticcheck` and `openfga` to the registry 

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/src/commands/setup.rs
Fixes https://github.com/moonrepo/proto/issues/646
=> fix: Fix `proto setup` issues.

CHANGELOG.md, crates/core/src/proto_config.rs
See moonrepo/proto#711
This is dependant on moonrepo/plugins#34 first being released, and assumes the released version of `schema_tool` is `0.16.4`. If this changes, this PR also needs updated.
*I have assumed this will be released as 0.45.2 when bumping the version - if not then this will affect moonrepo/moon#1820*
=> deps: Update schema tool version

.cargo/config.toml
The configuration only applies correctly for cross builds, I think.
Fixes #747
=> build: fix compilation on ARM Linux

package/src/api-types.ts, registry/data/third-party.json
Current `kubectl` plugin doesn't work since it uses old URL (storage.googleapis.com), which is [deprecated](https://github.com/kubernetes/k8s.io/issues/2396).
This commit replaces the `kubectl` plugin that uses new URL (dl.k8s.io) instead.
=> fix: replace `kubectl` plugin

crates/warpgate/src/helpers.rs, crates/warpgate/tests/helpers_test.rs
It seems to have issues when mixing forward and backwards separators. Standardize on forward.
=> fix: Fix path separators on windows WASM.

crates/cli/src/commands/run.rs, crates/cli/tests/run_test.rs
Addresses issue in: https://github.com/moonrepo/proto/issues/785
It seems that `run_global_tool` was not correctly catching the case a left over shim from some project was present, but there was no globally pinned version. When the user attempted to run the native binary proto would automatically detect that the plugin was one of the built in ones and run through the regular process likely to provide the auto install option. I updated `locate_tool` to ignore the built-in plugins check if it detects that it is running from a shim since a shim should imply that the user should have a pinned version in one of the config files.
=> fix: run_global_tool

crates/cli/src/main_shim.rs
This pull request refactors the logging mechanism in `crates/cli/src/main_shim.rs` by replacing the `debug` function with a `debug!` macro.
* **Introduction of `debug!` macro**: The `debug` function has been replaced with a macro to streamline logging calls and eliminate the need for closures. This change enhances performance, improves code readability, and reduces the binary size 😃.
-  Simply run `cargo build --bin proto-shim --release` and check the size. The macro version is even smaller:
```sh
➜  proto git:(op/shim-min-size) wc -c target/release/proto-shim target/release/proto-shim-origin 
487,872 target/release/proto-shim
487,920 target/release/proto-shim-origin
```
Surprisingly, both are smaller than the actual 564K released on GitHub.
After checking the release workflow, the …
=> refactor: Replace debug function with macro for improved logging and bin size

registry/data/third-party.json
Added 3 new `proto` plugins, all in TOML format:
- [`dbmate`](https://github.com/amacneil/dbmate)
- [`ruff`](https://docs.astral.sh/ruff/) (there is an existing `ruff` plugin by @Phault but cannot be used to install the latest version of `ruff`)
- [`vale`](https://vale.sh)
=> feat: new tools (dbmate, ruff, vale)

crates/cli/src/commands/install.rs, crates/cli/src/commands/run.rs, crates/cli/src/workflows/install_workflow.rs, crates/core/src/flow/detect.rs, crates/core/src/flow/install.rs, crates/core/src/flow/locate.rs, crates/core/src/flow/resolve.rs, crates/core/src/flow/setup.rs, crates/core/src/tool.rs, crates/pdk-api/src/api/mod.rs, crates/pdk-api/src/hooks.rs, crates/pdk-test-utils/src/wrapper.rs, crates/warpgate/src/plugin.rs
…and add documentation for convenience.
There are many plugin capabilities accessed via `tool.plugin.has_func("xxx")`, but we are hardcoding those function names in various places. This makes it challenging for plugin developers to identify them.
- Introduce enumeration of all available plugin functions that can be implemented by plugins.
- Enhanced documentation for all plugin function with its associated input/output types.
- Updated hardcoded strings with predefined `PluginFunction` and `HookFunction`
=> refactor: Use enum to unify function string literals.
